- id: git-chglog
  name: Generate CHANGELOG
  description: Generate CHANGELOG based on git commits and tags
  language: script
  require_serial: true
  pass_filenames: false
  entry: entry.sh
  args: ['--output', 'CHANGELOG.md']
